# Array creation routines

## Ones and zeros

In [1]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

array([[0, 0],
       [0, 0]])

Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [32]:
X = np.array([[1,2,3], [4,5,6]], np.int32)


array([[1, 2, 3],
       [4, 5, 6]])

Create a 3-D array with ones on the diagonal and zeros elsewhere.

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Create a new array of 3*2 float numbers, filled with ones.

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [59]:
x = np.arange(4, dtype=np.int64)


array([1, 1, 1, 1], dtype=int64)

Create a new array of 3*2 float numbers, filled with zeros.

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [58]:
x = np.arange(4, dtype=np.int64)


array([0, 0, 0, 0], dtype=int64)

Create a new array of 2*5 uints, filled with 6.

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [79]:
x = np.arange(4, dtype=np.int64)


array([6, 6, 6, 6], dtype=int64)

## From existing data

Create an array of [1, 2, 3].

array([1, 2, 3])

Let x = [1, 2]. Conver it into an array.

In [60]:
x = [1,2]


array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [62]:
X = np.array([[1, 2], [3, 4]])


matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [63]:
x = [1, 2]


array([ 1.,  2.])

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [67]:
x = np.array([30])


30

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [76]:
x = np.array([1, 2, 3])


70140352 [1 2 3]
70140752 [1 2 3]


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

array([  3.        ,   3.14285714,   3.28571429,   3.42857143,
         3.57142857,   3.71428571,   3.85714286,   4.        ,
         4.14285714,   4.28571429,   4.42857143,   4.57142857,
         4.71428571,   4.85714286,   5.        ,   5.14285714,
         5.28571429,   5.42857143,   5.57142857,   5.71428571,
         5.85714286,   6.        ,   6.14285714,   6.28571429,
         6.42857143,   6.57142857,   6.71428571,   6.85714286,
         7.        ,   7.14285714,   7.28571429,   7.42857143,
         7.57142857,   7.71428571,   7.85714286,   8.        ,
         8.14285714,   8.28571429,   8.42857143,   8.57142857,
         8.71428571,   8.85714286,   9.        ,   9.14285714,
         9.28571429,   9.42857143,   9.57142857,   9.71428571,
         9.85714286,  10.        ])

Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

array([  1.00000000e+03,   1.38038426e+03,   1.90546072e+03,
         2.63026799e+03,   3.63078055e+03,   5.01187234e+03,
         6.91830971e+03,   9.54992586e+03,   1.31825674e+04,
         1.81970086e+04,   2.51188643e+04,   3.46736850e+04,
         4.78630092e+04,   6.60693448e+04,   9.12010839e+04,
         1.25892541e+05,   1.73780083e+05,   2.39883292e+05,
         3.31131121e+05,   4.57088190e+05,   6.30957344e+05,
         8.70963590e+05,   1.20226443e+06,   1.65958691e+06,
         2.29086765e+06,   3.16227766e+06,   4.36515832e+06,
         6.02559586e+06,   8.31763771e+06,   1.14815362e+07,
         1.58489319e+07,   2.18776162e+07,   3.01995172e+07,
         4.16869383e+07,   5.75439937e+07,   7.94328235e+07,
         1.09647820e+08,   1.51356125e+08,   2.08929613e+08,
         2.88403150e+08,   3.98107171e+08,   5.49540874e+08,
         7.58577575e+08,   1.04712855e+09,   1.44543977e+09,
         1.99526231e+09,   2.75422870e+09,   3.80189396e+09,
         5.24807460e+09,

## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [93]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])


array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

Create an array which looks like below. array([[ 0., 0., 0., 0., 0.], [ 1., 0., 0., 0., 0.], [ 1., 1., 0., 0., 0.]])
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

# Array creation routines

## Ones and zeros

In [1]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [27]:
np.empty([2,2], int)

array([[0, 0],
       [0, 0]])

Let X = np.array([1,2,3], [4,5,6], np.int32). Create a new array with the same shape and type as X.

In [32]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
np.empty_like(X)

array([[1, 2, 3],
       [4, 5, 6]])

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [33]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [35]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Create a new array of 3*2 float numbers, filled with ones.

In [36]:
np.ones([3,2], float)

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [59]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1], dtype=int64)

Create a new array of 3*2 float numbers, filled with zeros.

In [45]:
np.zeros((3,2), float)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [58]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

Create a new array of 2*5 uints, filled with 6.

In [49]:
np.full((2, 5), 6, dtype=np.uint)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [50]:
np.ones([2, 5], dtype=np.uint) * 6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [79]:
x = np.arange(4, dtype=np.int64)
np.full_like(x, 6)

array([6, 6, 6, 6], dtype=int64)

In [81]:
np.ones_like(x) * 6

array([6, 6, 6, 6], dtype=int64)

## From existing data

Create an array of [1, 2, 3].

In [53]:
np.array([1, 2, 3])

array([1, 2, 3])

Let x = [1, 2]. Conver it into an array.

In [60]:
x = [1,2]
np.asarray(x)

array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [62]:
X = np.array([[1, 2], [3, 4]])
np.asmatrix(X)

matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [63]:
x = [1, 2]
np.asfarray(x)

array([ 1.,  2.])

In [64]:
np.asarray(x, float)

array([ 1.,  2.])

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [67]:
x = np.array([30])
np.asscalar(x)

30

In [68]:
x[0]

30

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [76]:
x = np.array([1, 2, 3])
y = np.copy(x)
print id(x), x
print id(y), y

70140352 [1 2 3]
70140752 [1 2 3]


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [85]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [86]:
np.linspace(3., 10, 50)

array([  3.        ,   3.14285714,   3.28571429,   3.42857143,
         3.57142857,   3.71428571,   3.85714286,   4.        ,
         4.14285714,   4.28571429,   4.42857143,   4.57142857,
         4.71428571,   4.85714286,   5.        ,   5.14285714,
         5.28571429,   5.42857143,   5.57142857,   5.71428571,
         5.85714286,   6.        ,   6.14285714,   6.28571429,
         6.42857143,   6.57142857,   6.71428571,   6.85714286,
         7.        ,   7.14285714,   7.28571429,   7.42857143,
         7.57142857,   7.71428571,   7.85714286,   8.        ,
         8.14285714,   8.28571429,   8.42857143,   8.57142857,
         8.71428571,   8.85714286,   9.        ,   9.14285714,
         9.28571429,   9.42857143,   9.57142857,   9.71428571,
         9.85714286,  10.        ])

Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

In [88]:
np.logspace(3., 10., 50, endpoint=False)

array([  1.00000000e+03,   1.38038426e+03,   1.90546072e+03,
         2.63026799e+03,   3.63078055e+03,   5.01187234e+03,
         6.91830971e+03,   9.54992586e+03,   1.31825674e+04,
         1.81970086e+04,   2.51188643e+04,   3.46736850e+04,
         4.78630092e+04,   6.60693448e+04,   9.12010839e+04,
         1.25892541e+05,   1.73780083e+05,   2.39883292e+05,
         3.31131121e+05,   4.57088190e+05,   6.30957344e+05,
         8.70963590e+05,   1.20226443e+06,   1.65958691e+06,
         2.29086765e+06,   3.16227766e+06,   4.36515832e+06,
         6.02559586e+06,   8.31763771e+06,   1.14815362e+07,
         1.58489319e+07,   2.18776162e+07,   3.01995172e+07,
         4.16869383e+07,   5.75439937e+07,   7.94328235e+07,
         1.09647820e+08,   1.51356125e+08,   2.08929613e+08,
         2.88403150e+08,   3.98107171e+08,   5.49540874e+08,
         7.58577575e+08,   1.04712855e+09,   1.44543977e+09,
         1.99526231e+09,   2.75422870e+09,   3.80189396e+09,
         5.24807460e+09,

## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [93]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

In [94]:
X.diagonal()

array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [95]:
np.diagflat([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [97]:
np.tri(3, 5, -1)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

Create an array which looks like below. array([[ 0., 0., 0., 0., 0.], [ 1., 0., 0., 0., 0.], [ 1., 1., 0., 0., 0.]])
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [101]:
np.tril(np.arange(1, 13).reshape(4, 3), -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [102]:
np.triu(np.arange(1, 13).reshape(4, 3), -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

# Array manipulation routines

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to zero. Reshape x so that the size of the second dimension equals 150.

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
   1.  1.  

Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

[1 4 2 5 3 6]


Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

5


Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


(4L, 3L, 5L)


Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

(4L, 3L)


Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

(3L, 1L, 4L)


Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

(3L, 4L)


Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

[[1 4]
 [2 5]
 [3 6]]


Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

[[[1 4]]

 [[2 5]]

 [[3 6]]]


Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

[array([[[ 0,  1,  2],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [12, 13, 14]]]), array([[[ 3],
        [ 7]],

       [[11],
        [15]]])]


Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

[0 0 1 1 2 2]


Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

[1 2 3 0 2 1]


Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


[1 2 3 4 5] [2 3 1 1 2]


Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

[[2 1]
 [4 3]]


Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

[[3 4]
 [1 2]]


Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

[[2 4]
 [1 3]]


Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

[[4 1 2 3]
 [8 5 6 7]]


# Array manipulation routines

In [5]:
import numpy as np

### Q1. Let x be a ndarray [10, 10, 3] with all elements set to zero. Reshape x so that the size of the second dimension equals 150.

In [7]:
x = np.ones([10, 10, 3])
out = np.reshape(x, [-1, 150])
print(out)
assert np.allclose(out, np.ones([10, 10, 3]).reshape([-1, 150]))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1.]]


### Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])
out1 = np.ravel(x, order='F')
out2 = np.ravel(x, order='F') #x.flatten(order="F")
assert np.allclose(out1, out2)
print(out1)


[1 4 2 5 3 6]


### Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
out1 = x.flat[4]
out2 = np.ravel(x)[4]
assert np.allclose(out1, out2)
print out1


### Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [ ]:
x = np.zeros((3, 4, 5))
out1 = np.swapaxes(x, 1, 0)
out2 = x.transpose([1, 0, 2])
assert out1.shape == out2.shape
print out1.shape

### Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [ ]:
x = np.zeros((3, 4))
out1 = np.swapaxes(x, 1, 0)
out2 = x.transpose()
out3 = x.T
assert out1.shape == out2.shape == out3.shape
print(out1.shape)

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [ ]:
x = np.zeros((3, 4))
print np.expand_dims(x, axis=1).shape

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [ ]:
x = np.zeros((3, 4, 1))
print np.squeeze(x).shape

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
out1 = np.concatenate((x, y), 1)
out2 = np.hstack((x, y))
assert np.allclose(out1, out2)
print out2

Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
out1 = np.concatenate((x, y), 0)
out2 = np.vstack((x, y))
assert np.allclose(out1, out2)
print out2

Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [ ]:
x = np.array((1,2,3))
y = np.array((4,5,6))
out1 = np.column_stack((x, y))
out2 = np.dstack((x, y))
out3 = np.vstack((x, y)).T
assert np.allclose(out1, out2)
assert np.allclose(out2, out3)
print out1


Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [ ]:
x = np.array([[1],[2],[3]])
y = np.array([[4],[5],[6]])
out = np.dstack((x, y))
print out


Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x = np.arange(1, 10)
print np.split(x, [4, 6])

Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

In [ ]:
x = np.arange(16).reshape(2, 2, 4)
out1 = np.split(x, [3],axis=2)
out2 = np.dsplit(x, [3])
assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])
print out1


Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [ ]:
x = np.arange(16).reshape((4, 4))
out1 = np.hsplit(x, 2)
out2 = np.split(x, 2, 1)
assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])
print out1

Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [ ]:
x = np.arange(16).reshape((4, 4))
out1 = np.vsplit(x, 2)
out2 = np.split(x, 2, 0)
assert np.allclose(out1[0], out2[0])
assert np.allclose(out1[1], out2[1])
print out1

Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [ ]:
x = np.array([0, 1, 2])
out1 = np.tile(x, [2, 2])
out2 = np.resize(x, [2, 6])
assert np.allclose(out1, out2)
print out1

Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [ ]:
x = np.array([0, 1, 2])
print np.repeat(x, 2)

Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [ ]:
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
out = np.trim_zeros(x)
print out

Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [ ]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])
u, indices = np.unique(x, return_counts=True)
print u, indices

Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [ ]:
x = np.array([[1,2], [3,4]])
out1 = np.fliplr(x)
out2 = x[:, ::-1]
assert np.allclose(out1, out2)
print out1

Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [ ]:
x = np.array([[1,2], [3,4]])
out1 = np.flipud(x)
out2 = x[::-1, :]
assert np.allclose(out1, out2)
print out1

Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [ ]:
x = np.array([[1,2], [3,4]])
out = np.rot90(x)
print out

Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [ ]:
x = np.arange(1, 9).reshape([2, 4])
print np.roll(x, 1, axis=1)

# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

## Matrix and vector products

Q1. Predict the results of the following code.

In [53]:
x = [1,2]
y = [[4, 1], [2, 2]]
#print np.dot(x, y)
#print np.dot(y, x)
#print np.matmul(x, y)
#print np.inner(x, y)
#print np.inner(y, x)

Q2. Predict the results of the following code.

In [52]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
#print np.dot(y, x)
#print np.matmul(y, x)


Q3. Predict the results of the following code.

In [37]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
#print np.vdot(x, y)
#print np.vdot(y, x)
#print np.dot(x.flatten(), y.flatten())
#print np.inner(x.flatten(), y.flatten())
#print (x*y).sum()

Q4. Predict the results of the following code.

In [45]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
#print np.inner(x, y)
#print np.inner(y, x)
#print np.outer(x, y)
#print np.outer(y, x)

## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [97]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)


[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


Q6. Compute the qr factorization of x and verify it.

In [107]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)


q=
[[-0.85714287  0.39428571  0.33142856]
 [-0.42857143 -0.90285712 -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r=
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [165]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)


U=
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
[ 3.          2.23606801  2.          0.        ] 
V=
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [77]:
x = np.diag((1, 2, 3))


eigenvalues are
[ 1.  2.  3.]
eigenvectors are
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Q9. Predict the results of the following code.

In [81]:
#print np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs)

## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [12]:
x = np.arange(1, 10).reshape((3, 3))


16.8819430161
4.56177073661e+17


Q11. Calculate the determinant of x.

In [22]:
x = np.arange(1, 5).reshape((2, 2))


-2.0


Q12. Calculate the rank of x.

In [35]:
x = np.eye(4)


4


Q13. Compute the sign and natural logarithm of the determinant of x.

In [49]:
x = np.arange(1, 5).reshape((2, 2))



-1.0 0.69314718056


Q14. Return the sum along the diagonal of x.

In [57]:
x = np.eye(4)


4.0


## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [60]:
x = np.array([[1., 2.], [3., 4.]])



[[-2.   1. ]
 [ 1.5 -0.5]]


# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

## Matrix and vector products

Q1. Predict the results of the following code.

In [61]:
x = [1,2]
y = [[4, 1], [2, 2]]
print np.dot(x, y)
print np.dot(y, x)
print np.matmul(x, y)
print np.inner(x, y)
print np.inner(y, x)

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [62]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print np.dot(y, x)
print np.matmul(y, x)


[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [63]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print np.vdot(x, y)
print np.vdot(y, x)
print np.dot(x.flatten(), y.flatten())
print np.inner(x.flatten(), y.flatten())
print (x*y).sum()

30
30
30
30
30


Q4. Predict the results of the following code.

In [65]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print np.inner(x, y)
print np.inner(y, x)
print np.outer(x, y)
print np.outer(y, x)

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [97]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
L = np.linalg.cholesky(x)
print L
assert np.array_equal(np.dot(L, L.T.conjugate()), x)

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


Q6. Compute the qr factorization of x and verify it.

In [107]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q, r = np.linalg.qr(x)
print "q=\n", q, "\nr=\n", r
assert np.allclose(np.dot(q, r), x)

q=
[[-0.85714287  0.39428571  0.33142856]
 [-0.42857143 -0.90285712 -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r=
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [165]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
U, s, V = np.linalg.svd(x, full_matrices=False)
print "U=\n", U, "\ns=\n", s, "\nV=\n", v
assert np.allclose(np.dot(U, np.dot(np.diag(s), V)), x)


U=
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
[ 3.          2.23606801  2.          0.        ] 
V=
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [68]:
x = np.diag((1, 2, 3))
eigenvals = np.linalg.eig(x)[0]
eigenvals_ = np.linalg.eigvals(x)
assert np.array_equal(eigenvals, eigenvals_)
print "eigenvalues are\n", eigenvals
eigenvecs = np.linalg.eig(x)[1]
print "eigenvectors are\n", eigenvecs

eigenvalues are
[ 1.  2.  3.]
eigenvectors are
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Q9. Predict the results of the following code.

In [69]:
print np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs)

True


## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [12]:
x = np.arange(1, 10).reshape((3, 3))
print np.linalg.norm(x, 'fro')
print np.linalg.cond(x, 'fro')

16.8819430161
4.56177073661e+17


Q11. Calculate the determinant of x.

In [22]:
x = np.arange(1, 5).reshape((2, 2))
out1 = np.linalg.det(x)
out2 = x[0, 0] * x[1, 1] - x[0, 1] * x[1, 0]
assert np.allclose(out1, out2)
print out1

-2.0


Q12. Calculate the rank of x.

In [35]:
x = np.eye(4)
out1 = np.linalg.matrix_rank(x)
out2 = np.linalg.svd(x)[1].size
assert out1 == out2
print out1


4


Q13. Compute the sign and natural logarithm of the determinant of x.

In [49]:
x = np.arange(1, 5).reshape((2, 2))
sign, logdet = np.linalg.slogdet(x)
det = np.linalg.det(x)
assert sign == np.sign(det)
assert logdet == np.log(np.abs(det))
print sign, logdet


-1.0 0.69314718056


Q14. Return the sum along the diagonal of x.

In [57]:
x = np.eye(4)
out1 = np.trace(x)
out2 = x.diagonal().sum()
assert out1 == out2
print out1

4.0


## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [60]:
x = np.array([[1., 2.], [3., 4.]])
out1 = np.linalg.inv(x)
assert np.allclose(np.dot(x, out1), np.eye(2))
print out1


[[-2.   1. ]
 [ 1.5 -0.5]]


# Logic functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

## Truth value testing


Q1. Let x be an arbitrary array. Return True if none of the elements of x is zero. Remind that 0 evaluates to False in python.


In [4]:
x = np.array([1,2,3])
#

x = np.array([1,0,3])
#

True
False


Q2. Let x be an arbitrary array. Return True if any of the elements of x is non-zero.

In [5]:
x = np.array([1,0,0])
#

x = np.array([0,0,0])
#

True
False


## Array contents


Q3. Predict the result of the following code.

In [8]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isfinite(x)

Q4. Predict the result of the following code.

In [10]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isinf(x)

Q5. Predict the result of the following code.

In [12]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isnan(x)

## Array type testing

Q6. Predict the result of the following code.

In [15]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
#print np.iscomplex(x)

Q7. Predict the result of the following code.

In [18]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
#print np.isreal(x)

Q8. Predict the result of the following code.

In [21]:
#print np.isscalar(3)
#print np.isscalar([3])
#print np.isscalar(True)

## Logical operations

Q9. Predict the result of the following code.

In [31]:
#print np.logical_and([True, False], [False, False])
#print np.logical_or([True, False, True], [True, False, False])
#print np.logical_xor([True, False, True], [True, False, False])
#print np.logical_not([True, False, 0, 1])


## Comparison

Q10. Predict the result of the following code.

In [42]:
#print np.allclose([3], [2.999999])
#print np.array_equal([3], [2.999999])

Q11. Write numpy comparison functions such that they return the results as you see.

In [51]:
x = np.array([4, 5])
y = np.array([2, 5])
#
#
#
#

[ True False]
[ True  True]
[False False]
[False  True]


Q12. Predict the result of the following code.

In [50]:
#print np.equal([1, 2], [1, 2.000001])
#print np.isclose([1, 2], [1, 2.000001])

# Logic functions

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

## Truth value testing


Q1. Let x be an arbitrary array. Return True if none of the elements of x is zero. Remind that 0 evaluates to False in python.


In [4]:
x = np.array([1,2,3])
print np.all(x)

x = np.array([1,0,3])
print np.all(x)

True
False


Q2. Let x be an arbitrary array. Return True if any of the elements of x is non-zero.

In [5]:
x = np.array([1,0,0])
print np.any(x)

x = np.array([0,0,0])
print np.any(x)

True
False


## Array contents


Q3. Predict the result of the following code.

In [8]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isfinite(x)

Q4. Predict the result of the following code.

In [10]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isinf(x)

Q5. Predict the result of the following code.

In [12]:
x = np.array([1, 0, np.nan, np.inf])
#print np.isnan(x)

## Array type testing

Q6. Predict the result of the following code.

In [15]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
#print np.iscomplex(x)

Q7. Predict the result of the following code.

In [18]:
x = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
#print np.isreal(x)

Q8. Predict the result of the following code.

In [21]:
#print np.isscalar(3)
#print np.isscalar([3])
#print np.isscalar(True)

## Logical operations

Q9. Predict the result of the following code.

In [31]:
#print np.logical_and([True, False], [False, False])
#print np.logical_or([True, False, True], [True, False, False])
#print np.logical_xor([True, False, True], [True, False, False])
#print np.logical_not([True, False, 0, 1])


## Comparison

Q10. Predict the result of the following code.

In [42]:
#print np.allclose([3], [2.999999])
#print np.array_equal([3], [2.999999])

Q11. Write numpy comparison functions such that they return the results as you see.

In [51]:
x = np.array([4, 5])
y = np.array([2, 5])
print np.greater(x, y)
print np.greater_equal(x, y)
print np.less(x, y)
print np.less_equal(x, y)


[ True False]
[ True  True]
[False False]
[False  True]


Q12. Predict the result of the following code.

In [50]:
#print np.equal([1, 2], [1, 2.000001])
#print np.isclose([1, 2], [1, 2.000001])

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

Q1. Search for docstrings of the numpy functions on linear algebra.

Search results for 'linear algebra'
-----------------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.restoredot
    Restore `dot`, `vdot`, and `innerproduct` to the default non-BLAS
numpy.linalg.eig
    Compute the eigenvalues and right eigenvectors of a square array.
numpy.linalg.cond
    Compute the condition number of a matrix.
numpy.linalg.eigh
    Return the eigenvalues and eigenvectors of a Hermitian or symmetric matrix.
numpy.linalg.pinv
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
numpy.linalg.LinAlgError
    Generic Python-exception-derived object raised by linalg functions.


Q2. Get help information for numpy dot function.

dot(a, b, out=None)

Dot product of two arrays.

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D
arrays to inner product of vectors (without complex conjugation). For
N dimensions it is a sum product over the last axis of `a` and
the second-to-last of `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

Parameters
----------
a : array_like
    First argument.
b : array_like
    Second argument.
out : ndarray, optional
    Output argument. This must have the exact kind that would be returned
    if it was not used. In particular, it must have the right type, must be
    C-contiguous, and its dtype must be the dtype that would be returned
    for `dot(a,b)`. This is a performance feature. Therefore, if these
    conditions are not met, an exception is raised, instead of attempting
    to be flexible.

Returns
-------
output : ndarray
    Returns the dot product of `a` and `b`.  If `a` and `b` are both
    scalars or both 1-D arrays then a scalar is returned; ot

In [1]:
import numpy as np

In [2]:
np.__version__

'1.11.2'

Q1. Search for docstrings of the numpy functions on linear algebra.

In [4]:
np.lookfor('linear algebra')

Search results for 'linear algebra'
-----------------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.
numpy.poly
    Find the coefficients of a polynomial with the given sequence of roots.
numpy.restoredot
    Restore `dot`, `vdot`, and `innerproduct` to the default non-BLAS
numpy.linalg.eig
    Compute the eigenvalues and right eigenvectors of a square array.
numpy.linalg.cond
    Compute the condition number of a matrix.
numpy.linalg.eigh
    Return the eigenvalues and eigenvectors of a Hermitian or symmetric matrix.
numpy.linalg.pinv
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
numpy.linalg.LinAlgError
    Generic Python-exception-derived object raised by linalg functions.


Q2. Get help information for numpy dot function.

In [9]:
np.info(np.dot)

dot(a, b, out=None)

Dot product of two arrays.

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D
arrays to inner product of vectors (without complex conjugation). For
N dimensions it is a sum product over the last axis of `a` and
the second-to-last of `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

Parameters
----------
a : array_like
    First argument.
b : array_like
    Second argument.
out : ndarray, optional
    Output argument. This must have the exact kind that would be returned
    if it was not used. In particular, it must have the right type, must be
    C-contiguous, and its dtype must be the dtype that would be returned
    for `dot(a,b)`. This is a performance feature. Therefore, if these
    conditions are not met, an exception is raised, instead of attempting
    to be flexible.

Returns
-------
output : ndarray
    Returns the dot product of `a` and `b`.  If `a` and `b` are both
    scalars or both 1-D arrays then a scalar is returned; ot

# Random Sampling

In [2]:
import numpy as np

In [3]:
np.__version__

'1.11.2'

In [5]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

array([[ 0.13879034,  0.71300174],
       [ 0.08121322,  0.00393554],
       [ 0.02349471,  0.56677474]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

-0.00110028519551
0.999683483393


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

array([[1, 3],
       [3, 0],
       [0, 0]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [3]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']


5 out of 10
2 out of 10
3 out of 10
5 out of 10
2 out of 10
5 out of 10
2 out of 10
2 out of 10
2 out of 10
5 out of 10


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

array([5, 4, 0])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

[2 3 8 4 5 1 0 6 9 7]


In [88]:
# Or


[5 2 7 4 1 0 6 8 9 3]


## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

# Random Sampling

In [2]:
import numpy as np

In [3]:
np.__version__

'1.11.2'

In [5]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [49]:
np.random.rand(3, 2) 
# Or np.random.random((3,2))

array([[ 0.13879034,  0.71300174],
       [ 0.08121322,  0.00393554],
       [ 0.02349471,  0.56677474]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [42]:
out1 = np.random.randn(1000, 1000)
out2 = np.random.standard_normal((1000, 1000))
out3 = np.random.normal(loc=0.0, scale=1.0, size=(1000, 1000))
assert np.allclose(np.mean(out1), np.mean(out2), atol=0.1)
assert np.allclose(np.mean(out1), np.mean(out3), atol=0.1)
assert np.allclose(np.std(out1), np.std(out2), atol=0.1)
assert np.allclose(np.std(out1), np.std(out3), atol=0.1)
print np.mean(out3)
print np.std(out1)


-0.00110028519551
0.999683483393


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [44]:
np.random.randint(0, 4, (3, 2))

array([[1, 3],
       [3, 0],
       [0, 0]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [58]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']

In [60]:
for _ in range(10):
    print np.random.choice(x, p=[.3, .5, .2])

2 out of 10
5 out of 10
3 out of 10
5 out of 10
5 out of 10
5 out of 10
2 out of 10
2 out of 10
5 out of 10
5 out of 10


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

In [66]:
np.random.choice(10, 3, replace=False)

array([5, 4, 0])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [86]:
x = np.arange(10)
np.random.shuffle(x)
print x

[2 3 8 4 5 1 0 6 9 7]


In [88]:
# Or
print np.random.permutation(10)

[5 2 7 4 1 0 6 8 9 3]


## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [91]:
np.random.seed(10)

# Set routines

In [4]:
import numpy as np

In [5]:
np.__version__

'1.11.2'

In [6]:
author = 'kyubyong. longinglove@nate.com'

## Making proper sets

Q1. Get unique elements and reconstruction indices from x. And reconstruct x.

In [15]:
x = np.array([1, 2, 6, 4, 2, 3, 2])



unique elements = [1 2 3 4 6]
reconstruction indices = [0 1 4 3 1 2 1]
reconstructed = [1 2 6 4 2 3 2]


## Boolean operations

Q2. Create a boolean array of the same shape as x. If each element of x is present in y, the result will be True, otherwise False.

In [19]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1])


[ True  True False False  True]


Q3. Find the unique intersection of x and y.

In [20]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])


[0 1]


Q4. Find the unique elements of x that are not present in y.

In [21]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])


[2 5]


Q5. Find the xor elements of x and y.

In [40]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
out1 = np.setxor1d(x, y)
out2 = np.sort(np.concatenate((np.setdiff1d(x, y), np.setdiff1d(y, x))))
assert np.allclose(out1, out2)



[2 4 5]


Q6. Find the union of x and y.

In [42]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
out1 = np.union1d(x, y)
out2 = np.sort(np.unique(np.concatenate((x, y))))
assert np.allclose(out1, out2)


[0 1 2 4 5]


# Set routines

In [4]:
import numpy as np

In [5]:
np.__version__

'1.11.2'

In [6]:
author = 'kyubyong. longinglove@nate.com'

## Making proper sets

Q1. Get unique elements and reconstruction indices from x. And reconstruct x.

In [15]:
x = np.array([1, 2, 6, 4, 2, 3, 2])
out, indices = np.unique(x, return_inverse=True)
print "unique elements =", out
print "reconstruction indices =", indices
print "reconstructed =", out[indices]


unique elements = [1 2 3 4 6]
reconstruction indices = [0 1 4 3 1 2 1]
reconstructed = [1 2 6 4 2 3 2]


## Boolean operations

Q2. Create a boolean array of the same shape as x. If each element of x is present in y, the result will be True, otherwise False.

In [19]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1])
print np.in1d(x, y)

[ True  True False False  True]


Q3. Find the unique intersection of x and y.

In [20]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
print np.intersect1d(x, y)

[0 1]


Q4. Find the unique elements of x that are not present in y.

In [21]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
print np.setdiff1d(x, y)

[2 5]


Q5. Find the xor elements of x and y.

In [40]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
out1 = np.setxor1d(x, y)
out2 = np.sort(np.concatenate((np.setdiff1d(x, y), np.setdiff1d(y, x))))
assert np.allclose(out1, out2)
print out1


[2 4 5]


Q6. Find the union of x and y.

In [42]:
x = np.array([0, 1, 2, 5, 0])
y = np.array([0, 1, 4])
out1 = np.union1d(x, y)
out2 = np.sort(np.unique(np.concatenate((x, y))))
assert np.allclose(out1, out2)
print np.union1d(x, y)

[0 1 2 4 5]


# Array creation routines

In [1]:
import numpy as np

### Q1. Create a new array of 2*2 integers, without initializing entries.

In [4]:
def q1():
    '''
    This is a test:
    >>> q1()
    array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
    '''
    return np.empty([2,2], dtype=int)

In [5]:
import doctest
doctest.testmod(verbose=True)

Trying:
    q1()
Expecting:
    array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
**********************************************************************
File "__main__", line 4, in __main__.q1
Failed example:
    q1()
Expected:
    array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
            1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
Got:
    array([[-5764607523034234880,  1152930277147583419],
           [ 3401169227572248578,      571720283089260]])
1 items had no tests:
    __main__
**********************************************************************
1 items had failures:
   1 of   1 in __main__.q1
1 tests in 2 items.
0 passed and 1 failed.
***Test Failed*** 1 failures.


TestResults(failed=1, attempted=1)